// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGRjGyVoRK2uPovXx-vowd1zuw1QNhIsQ',
    appId: '1:1009521939221:web:949552ea36cc3cc8b0cf1c',
    messagingSenderId: '1009521939221',
    projectId: 'fir-conn-ac51d',
    authDomain: 'fir-conn-ac51d.firebaseapp.com',
    storageBucket: 'fir-conn-ac51d.firebasestorage.app',
    measurementId: 'G-54S4M2E1E8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0e_ang_wWyFqOWJ5mRBCqyra05b4nZpM',
    appId: '1:1009521939221:android:16b7484ca535b0b2b0cf1c',
    messagingSenderId: '1009521939221',
    projectId: 'fir-conn-ac51d',
    storageBucket: 'fir-conn-ac51d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMkdJbCepFcM6kIvJAaFVEu2Iu2LYVafY',
    appId: '1:1009521939221:ios:2c0aa30980c134f8b0cf1c',
    messagingSenderId: '1009521939221',
    projectId: 'fir-conn-ac51d',
    storageBucket: 'fir-conn-ac51d.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseConn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMkdJbCepFcM6kIvJAaFVEu2Iu2LYVafY',
    appId: '1:1009521939221:ios:2c0aa30980c134f8b0cf1c',
    messagingSenderId: '1009521939221',
    projectId: 'fir-conn-ac51d',
    storageBucket: 'fir-conn-ac51d.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseConn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGRjGyVoRK2uPovXx-vowd1zuw1QNhIsQ',
    appId: '1:1009521939221:web:12d7806b341e7a0cb0cf1c',
    messagingSenderId: '1009521939221',
    projectId: 'fir-conn-ac51d',
    authDomain: 'fir-conn-ac51d.firebaseapp.com',
    storageBucket: 'fir-conn-ac51d.firebasestorage.app',
    measurementId: 'G-S00RJH252Y',
  );
}
